//const Persona = require('./persona')
const Carro = require('./carro')
const Libro = require('./libros')
const Pelicula = require('./pelicula')
var persona = require('./persona')
const Ropa = require('./ropa')
const Serie = require('./series')
const Universidad = require('./universidad')

console.log(persona)
console.log(Libro)
console.log(Pelicula)
console.log(Carro)
console.log(Universidad)
console.log(Serie)
console.log(Ropa)