//const Persona = require('./persona')
const Carro = require('./carro')
const Libro = require('./libros')
const Pelicula = require('./pelicula')
var persona = require('./persona')

console.log(persona)
console.log(Libro)
console.log(Pelicula)
console.log(Carro)